src/appDeprecatedKeys.ts
src/apps/com.sina.weibo.ts

feat(微博): 全屏广告-连续签到

---

src/apps/com.apkpure.aegon.ts

https://i.gkd.li/i/13466610
https://i.gkd.li/i/15542026

feat(APKPure): 扩大”点击关闭“规则的匹配范围，在Key3：“分段广告-更新界面软件推荐”中

---

src/apps/com.mcdonalds.gma.cn.ts

feat(麦当劳): 权限提示-设备信息权限

---

src/apps/com.tencent.mobileqq.ts

对QQ近期常见的聊天页面关键词广告进行适配

---

src/globalDefaultApps.ts

* 添加了部分无需应用全局规则的应用
* 增补小米系统自带非系统应用 - `三方应用异常分析`

feat: applist

---

pnpm-lock.yaml
src/apps/com.taobao.htao.android.ts

feat(淘宝Lite): 其他-关闭切换站点提示

---

src/apps/com.intsig.camscanner.ts

第一条规则应该是支持`fastQuery`的，但是快照似乎太老了。刚刚试图截取，但也没看到广告。

perf: 扫描全能王

---

src/apps/com.tencent.mobileqq.ts

feat(QQ): 局部广告-动态页-卡片广告（补充规则）

---

src/apps/com.autonavi.minimap.ts

fix(高德地图): 全屏广告-弹窗广告

---

src/apps/com.tencent.mm.ts
src/globalDefaultApps.ts

同时也更新了AppList。不过是否需要把游戏类的应用也添加至黑名单中，以便默认禁用规则呢？

feat(微信): 分段广告-订阅号消息内容-广告（补充activityId）

---

src/apps/com.autonavi.minimap.ts

该消息推送似乎只会在刚打开应用时出现一次，关闭后似乎不会再次出现，因此如此设置

feat(高德地图): 局部广告-首页上方消息提醒（补充规则）

---

src/apps/com.sf.activity.ts

chore(顺丰速运): 新增快照、移除规则名称

---

src/apps/com.netease.cloudmusic.ts

Rule effects:
https://github.com/user-attachments/assets/978c986d-cb64-4881-8820-205efa1a4e50

feat(Netease Cloud Music): Support skip splash ads when app's language is set to English

---

src/apps/com.tencent.mobileqq.ts

feat(QQ): 功能类-开启推荐，发现可能认识的人

---

src/apps/com.hihonor.baidu.browser.ts

feat(荣耀浏览器): 开屏广告

---

src/apps/com.ximalaya.ting.android.ts

feat: 关闭喜马拉雅免流广告

---

CONTRIBUTING.md
README.md

fix: 修改一些过时内容

---

src/apps/com.wanbangauto.chargepile.ts

顺便请问： xxx1  >  xxx2  >  xxx3  和  xxx3 < xxx2 < xxx1 性能有区别吗
似乎没有，没有在api手册找到依据

feat(星星充电): 跳过全局广告和签到提示

---

src/apps/com.qinlin.edoor.ts

add and perf qin lin open rule

add and perf qin lin open rule

---

src/apps/com.qinlin.edoor.ts

Qin lin open

---

src/apps/com.chinarailway.globalticketing.ts
src/globalDefaultApps.ts

feat: 铁路12306-其他-关闭公告

---

src/apps/cn.com.bmac.nfc.ts
src/globalDefaultApps.ts

feat: 北京一卡通-全屏广告-弹窗广告

---

src/apps/com.coloros.phonemanager.ts

https://i.gkd.li/i/19749344
我是一加的手机，其他OPPO界面ID可能不一样。。

feat: OPPO手机管家-风险应用提示

---

.github/workflows/build_release.yml

chore: fix  build_release.yml

---

src/globalDefaultApps.ts

Signal 没有开屏广告，且当前规则会误触输入 PIN 时的 skip 按钮。
[Signal_MainActivity-1745852425481.1.zip](https://github.com/user-attachments/files/19942522/Signal_MainActivity-1745852425481.1.zip)

feat(Signal): 为 Signal 设置例外

---

src/apps/com.zhihu.android.ts

fix(知乎): 局部广告-信息流广告 部分失效

---

src/apps/com.eg.android.AlipayGphone.ts

fix(支付宝): 全屏广告-"下次支付用花呗"弹窗 部分失效

---

src/apps/pro.cubox.androidapp.ts

feat: Cubox-会员订阅界面

---

src/apps/com.jiaohua_browser.ts

feat: JMcomic全屏、横幅广告及功能类

---

src/apps/com.weilaishanhai.oopz.ts

Oopz 有的开屏广告是分段式的，但是很模板化，这个规则测试了很多次均可解决这种偶然发生的分段广告。

fix: Oopz-分段广告

---

src/apps/tv.danmaku.bili.ts

b站权限提示-通知权限增加activityIds

---

src/apps/com.oplus.appdetail.ts

自动点击查看详情和勾选已知悉风险，最后一步“仍然安装”不点。
https://i.gkd.li/i/22377327 这个界面不知道为什么延迟挺大而且经常失败..加actionDelay成功率高一点
加actionMaximum和actionMaximum是因为按默认的会退不出来
能否帮忙看下有没有更好的方法(´。＿。｀)

feat(一加应用安装器): 中高风险应用安装

---

src/apps/com.zjwh.android_wh_physicalfitness.ts

这个广告几乎会出现在这个应用的任何 Activity 中，我想直接把 `activityIds` 留空，但似乎没有其他软件这么写。
@AIsouler 你怎么看

feat: 运动世界校园-全屏广告

---

src/apps/com.heytap.health.ts

perf: OPPO健康-更新提示
